services:
  - type: web
    name: digicoop-staging-website
    runtime: static
    repo: https://github.com/Digicoops/dashboard
    branch: main
    rootDir: apps/frontend
    staticPublishPath: ./dist/digicoop/browser
    buildCommand: npm ci && npm run build -- --configuration production
    startCommand: NODE_ENV=production npm start
    autoDeployTrigger: checksPass

